In [6]:
import os

# Show all Kaggle input folders
print(os.listdir('/kaggle/input'))

['datasets']

In [7]:
import pandas as pd

# Load dataset
df = pd.read_csv('/kaggle/input/datasets/imranalishahh/marketing-and-product-performance-dataset/marketing_and_product_performance.csv')

# Show first 5 rows
df.head()

,Campaign_ID,Product_ID,Budget,Clicks,Conversions,Revenue_Generated,ROI,Customer_ID,Subscription_Tier,Subscription_Length,Flash_Sale_ID,Discount_Level,Units_Sold,Bundle_ID,Bundle_Price,Customer_Satisfaction_Post_Refund,Common_Keywords
0,CMP_RLSDVN,PROD_HBJFA3,41770.45,4946,73,15520.09,1.94,CUST_1K7G39,Premium,4,FLASH_1VFK5K,43,34,BNDL_29U6W5,433.80,4,Affordable
1,CMP_JHHUE9,PROD_OE8YNJ,29900.93,570,510,30866.17,0.76,CUST_0DWS6F,Premium,4,FLASH_1M6COK,28,97,BNDL_ULV60J,289.29,2,Innovative
2,CMP_6SBOWN,PROD_4V8A08,22367.45,3546,265,32585.62,1.41,CUST_BR2GST,Basic,9,FLASH_J4PEON,51,160,BNDL_0HY0EF,462.87,4,Affordable
3,CMP_Q31QCU,PROD_A1Q6ZB,29957.54,2573,781,95740.12,3.32,CUST_6TBY6K,Premium,32,FLASH_1TOVXT,36,159,BNDL_AI09BC,334.16,1,Durable
4,CMP_AY0UTJ,PROD_F57N66,36277.19,818,79,81990.43,3.53,CUST_XASI45,Standard,29,FLASH_AOBHXL,20,52,BNDL_R03ITT,371.67,2,Affordable

In [8]:
# Remove unnecessary ID columns

df = df.drop([
    'Campaign_ID',
    'Product_ID',
    'Customer_ID',
    'Flash_Sale_ID',
    'Bundle_ID'
], axis=1)

# Display remaining columns
print(df.columns)

Index(['Budget', 'Clicks', 'Conversions', 'Revenue_Generated', 'ROI',
       'Subscription_Tier', 'Subscription_Length', 'Discount_Level',
       'Units_Sold', 'Bundle_Price', 'Customer_Satisfaction_Post_Refund',
       'Common_Keywords'],
      dtype='object')

In [9]:
from sklearn.preprocessing import LabelEncoder

# Create encoder
le = LabelEncoder()

# Convert text columns into numbers
df['Subscription_Tier'] = le.fit_transform(df['Subscription_Tier'])
df['Common_Keywords'] = le.fit_transform(df['Common_Keywords'])

# Display first 5 rows
df.head()

,Budget,Clicks,Conversions,Revenue_Generated,ROI,Subscription_Tier,Subscription_Length,Discount_Level,Units_Sold,Bundle_Price,Customer_Satisfaction_Post_Refund,Common_Keywords
0,41770.45,4946,73,15520.09,1.94,1,4,43,34,433.80,4,0
1,29900.93,570,510,30866.17,0.76,1,4,28,97,289.29,2,2
2,22367.45,3546,265,32585.62,1.41,0,9,51,160,462.87,4,0
3,29957.54,2573,781,95740.12,3.32,1,32,36,159,334.16,1,1
4,36277.19,818,79,81990.43,3.53,2,29,20,52,371.67,2,0

In [10]:
# Features (input variables)
X = df.drop('Customer_Satisfaction_Post_Refund', axis=1)

# Target variable
y = df['Customer_Satisfaction_Post_Refund']

# Display first 5 rows
print(X.head())
print(y.head())

     Budget  Clicks  Conversions  Revenue_Generated   ROI  Subscription_Tier  \
0  41770.45    4946           73           15520.09  1.94                  1
1  29900.93     570          510           30866.17  0.76                  1
2  22367.45    3546          265           32585.62  1.41                  0
3  29957.54    2573          781           95740.12  3.32                  1
4  36277.19     818           79           81990.43  3.53                  2

   Subscription_Length  Discount_Level  Units_Sold  Bundle_Price  \
0                    4              43          34        433.80
1                    4              28          97        289.29
2                    9              51         160        462.87
3                   32              36         159        334.16
4                   29              20          52        371.67

   Common_Keywords
0                0
1                2
2                0
3                1
4                0
0    4
1    2
2    4
3    1
4    2
Name: Customer_Satisfaction_Post_Refund, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

# Split dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Display shapes
print("Training Features Shape:", X_train.shape)
print("Testing Features Shape:", X_test.shape)
print("Training Target Shape:", y_train.shape)
print("Testing Target Shape:", y_test.shape)

Training Features Shape: (8000, 11)
Testing Features Shape: (2000, 11)
Training Target Shape: (8000,)
Testing Target Shape: (2000,)

In [32]:
from sklearn.tree import DecisionTreeClassifier

# Create Decision Tree model
model = DecisionTreeClassifier(random_state=42)

# Train the model
model.fit(X_train, y_train)

print("Decision Tree Model Trained Successfully!")

Decision Tree Model Trained Successfully!

In [33]:
# Make predictions using test data

y_pred = model.predict(X_test)

# Display first 10 predictions
print(y_pred[:10])

[4 1 1 2 1 3 4 3 2 4]

In [34]:
from sklearn.metrics import accuracy_score

# Calculate model accuracy
accuracy = accuracy_score(y_test, y_pred)

# Print accuracy
print("Model Accuracy:", accuracy)

Model Accuracy: 0.253

In [35]:
from sklearn.metrics import classification_report

# Generate classification report
report = classification_report(y_test, y_pred)

# Print report
print(report)

              precision    recall  f1-score   support

           1       0.24      0.25      0.24       476
           2       0.26      0.28      0.27       490
           3       0.26      0.24      0.25       529
           4       0.25      0.24      0.25       505

    accuracy                           0.25      2000
   macro avg       0.25      0.25      0.25      2000
weighted avg       0.25      0.25      0.25      2000

In [36]:
from sklearn.metrics import confusion_matrix

# Create confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print confusion matrix
print(cm)

[[119 122 110 125]
 [116 139 113 122]
 [144 144 126 115]
 [124 126 133 122]]